
name: Umweltmonitoring
services:
  timescale:
    image: timescale/timescaledb:latest-pg15
    container_name: env_monitoring_db
    environment:
      - POSTGRES_DB=env_monitoring
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"  # 5433:5432
    volumes:
      - /var/lib/postgresql/data
    restart: always
    networks:
      - app-network

  app:
    container_name: SensboxDASH
    build:
      context: .
      dockerfile: ./Dockerfile
    #entrypoint: ["python code/DASH.py"]

    #volumes:
    #  - /UmApp:/app

networks:
  app-network:
    driver: bridge

volumes:
  timescaledb_data:

